### ISSUE TITLE
Environment variables to configure the valkey container

### ISSUE THREAD

**Issue by Xe** [valkey-io/valkey-container#26]
I'm trying to move over from the bitnami container to the official valkey container and I'm running into an issue where I need to configure the valkey server, but [can't find valkey server configuration docs on the website](https://valkey.io/docs/). Do I use the [redis docs](https://redis.io/docs/latest/operate/oss_and_stack/management/config-file/) for this?

I'd love to be able to use environment variables [like the bitnami container does](https://hub.docker.com/r/bitnami/valkey). This would let me shove everything in a ConfigMap like this:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: valkey-secret
data:
  VALKEY_PASSWORD: hunter2
```

Then just set those envvars on the deployment and it Just Works™️.
