### ISSUE TITLE
Docker pre-seeding with valkey

### ISSUE THREAD

**Issue by et311** [valkey-io/valkey-container#49]
Hey!

So im tryin to pre-seed my docker valkey db but ive been looking for a few hours now and the only results i get are amazon, valley seeds, and sql seeding.

Can someone plz help me? 

so far ive done the docker-compose.yml and i know i only need to "Set points "0"" in my db when i compose up and it cant be done manualy after i compose up, it must be automated

**Comment by parimoh** [comment]
You could probably do something like the following to run a script on `docker-compose up` to seed the db:

```
version: '3.8'

services:
  valkey:
    image: valkey/valkey
    container_name: valkey
    ports:
      - "6379:6379"

  seed:
    image: valkey/valkey
    depends_on:
      - valkey
    volumes:
      - ./seed.sh:/seed.sh
    entrypoint: [ "sh", "/seed.sh" ]
```

And then the script might look something like this:

```
#!/bin/sh
echo "Waiting for Valkey to be ready..."

# Wait until Valkey is accepting connections
until redis-cli -h valkey ping | grep PONG > /dev/null 2>&1; do
  sleep 1
done

echo "Valkey is ready. Seeding data..."
redis-cli -h valkey SET points 0
echo "Seeding complete."
```

This is the output I get from docker:

<img width="649" height="269" alt="Image" src="https://github.com/user-attachments/assets/af706043-586d-4f01-b0df-e09c3c91fcd4" />

And then when I attach a shell to the process I can see that `points` has a value:

<img width="257" height="90" alt="Image" src="https://github.com/user-attachments/assets/fad8500c-f161-42dd-b73f-6efca6ad5c3b" />


Let me know if you encounter any issues or have any questions
